swagger: "2.0"
info:
  version: 1.0.0
  title: "Trentose2jan12-176140"
  description: Esame, gestione astronauti su base spaziale
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://exams.jointresearch.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: trentose2jan12-176140.herokuapp.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /astronauts/{id}/:
    get:
      description: Return the info about an astronaut specified by the id
      operationId: getAstronaut
      parameters:
        - name: id
          in: path
          description: ID of astronaut to fetch
          required: true
          type: integer
          format: int32
          x-example: 23
      responses:
        200:
          description: Infos of the astronaut
          schema:
            $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Modify the info about an astronaut specified by the id
      operationId: modifyAstronaut
      parameters:
        - name: id
          in: path
          description: ID of astronaut to modify
          required: true
          type: integer
          format: int32
          x-example: 23
        - name: astronaut
          in: body
          description: astronaut
          required: true
          schema:
            $ref: '#/definitions/Astronaut'
      responses:
        202:
          description: astronaut update response
          schema:
            $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /astronauts:
    get:
      description: Return the info about all the astronaut(or someone filtered by lastName)
      operationId: getAstronauts
      parameters:
        - name: lastName
          in: query
          description: lastName of astronaut to fetch
          required: false
          type: string
      responses:
        200:
          description: Infos of the astronauts
          schema:
            type: array
            items:
              $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Add an astronaut
      operationId: addAstronaut
      parameters:
        - name: astronaut
          in: body
          description: new astronaut
          required: true
          schema:
            $ref: '#/definitions/NewAstronaut'
      responses:
        202:
          description: astronaut created response
          schema:
            $ref: '#/definitions/Astronaut'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Astronaut:
    allOf:
      - $ref: '#/definitions/NewAstronaut'
      - required:
        - astronautID
        properties:
          assignmentID:
            type: string
          dateUpdated: 
            type: string
            format: date-time  
  NewAstronaut:
    required:
      - firstName
      - lastName
      - isInSpace
    properties:
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string